# Prepare municipality-level data for Rondônia

This notebook filters the national outpatient dataset to include only records from Rondônia.

The resulting dataset is aggregated by municipality and only used to create the municipality-level choropleth map in the second step of the scrollytelling visualization.

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("sia-data.csv")
df.head()

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus
0,2024,5,SP,São Paulo,3550308,São Paulo,2078015,F630,NaN,NaN,M,28,1,0,1,3550308,São Paulo,5403010,1
1,2022,10,MA,Maranhão,2106755,Miranda do Norte,6569862,F630,NaN,NaN,M,21,3,0,0,2106755,Miranda do Norte,65495000,1
2,2022,9,BA,Bahia,2905701,Camaçari,7781555,F630,NaN,NaN,M,26,3,0,0,2905701,Camaçari,42809382,1
3,2024,10,SC,Santa Catarina,4209003,Joaçaba,3757412,NaN,NaN,F630,M,35,3,0,0,4209003,Joaçaba,89600000,1
4,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,64,3,0,0,1100288,Rolim de Moura,76940000,1

In [6]:
df.loc[df["ano"] == 2025, "mes"].unique()

array([ 9, 11, 10,  8,  2,  7,  5,  4,  1,  6,  3])

In [ ]:
df_ufs = df.groupby("sigla_uf").size().sort_values(ascending=False)
df_ufs

sigla_uf
SP    3273
RO    1166
MG     520
RS     434
PR     267
SC     247
PE     233
GO     181
PB     136
PI     109
CE     108
BA     108
MS      98
PA      98
RJ      95
MA      80
MT      71
AL      64
TO      52
AM      41
SE      21
DF      12
RN       9
RR       8
ES       7
AC       5
dtype: int64

In [ ]:
df_ro = df[df["sigla_uf"] == "RO"]
df_ro

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus
4,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,64,3,0,0,1100288,Rolim de Moura,76940000,1
5,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,M,75,1,0,0,1100288,Rolim de Moura,76940000,1
6,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,64,3,0,0,1100288,Rolim de Moura,76940000,1
7,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,60,3,0,0,1100288,Rolim de Moura,76940000,1
8,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,63,3,0,0,1100288,Rolim de Moura,76940000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6951,2025,2,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,79,4,0,0,1100288,Rolim de Moura,76940000,1
7388,2025,5,RO,Rondônia,1100049,Cacoal,5684471,F630,NaN,NaN,F,84,3,0,0,1100049,Cacoal,99999999,1
7389,2025,5,RO,Rondônia,1100049,Cacoal,5684471,F630,NaN,NaN,F,84,3,0,0,1100049,Cacoal,99999999,1
7390,2025,5,RO,Rondônia,1100049,Cacoal,5684471,F630,NaN,NaN,F,84,3,0,0,1100049,Cacoal,99999999,1
7391,2025,5,RO,Rondônia,1100049,Cacoal,5684471,F630,NaN,NaN,F,84,3,0,0,1100049,Cacoal,99999999,1

In [ ]:
df_ro["nome_municipio"].value_counts()

nome_municipio
Rolim de Moura       1152
Porto Velho             4
Cacoal                  4
Buritis                 2
Vilhena                 1
Ji-Paraná               1
Presidente Médici       1
Nova Mamoré             1
Name: count, dtype: int64

In [ ]:
df_ro.to_csv("df_ro_state.csv")