# SIA data analysis

This notebook analyzes the outpatient records extracted from the Outpatient Information System (SIA) to produce the main national indicators used in the project.

The notebook summarizes outpatient visits related to gambling and betting across Brazil between **2015 and 2025**, using the ICD-10 codes:

- **F63.0** — Pathological gambling
- **Z72.6** — Gambling and betting habits

The analysis includes both primary and associated diagnoses.

This notebook produces the datasets and summary statistics used in the story, including:

- National time series of outpatient visits (2015–2025)
- Total number of outpatient visits
- Distribution of ICD-10 codes (primary vs. associated diagnosis)

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("sia-data.csv")
df.head()

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus
0,2024,5,SP,São Paulo,3550308,São Paulo,2078015,F630,NaN,NaN,M,28,1,0,1,3550308,São Paulo,5403010,1
1,2022,10,MA,Maranhão,2106755,Miranda do Norte,6569862,F630,NaN,NaN,M,21,3,0,0,2106755,Miranda do Norte,65495000,1
2,2022,9,BA,Bahia,2905701,Camaçari,7781555,F630,NaN,NaN,M,26,3,0,0,2905701,Camaçari,42809382,1
3,2024,10,SC,Santa Catarina,4209003,Joaçaba,3757412,NaN,NaN,F630,M,35,3,0,0,4209003,Joaçaba,89600000,1
4,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,64,3,0,0,1100288,Rolim de Moura,76940000,1

In [29]:
df.shape

(7443, 19)

In [30]:
df.groupby("ano").size()

ano
2015     100
2016     123
2017      85
2018     120
2019     156
2020     118
2021     637
2022     953
2023    1479
2024    1463
2025    2209
dtype: int64

In [31]:
df.loc[df["ano"] == 2025, "mes"].unique()

array([ 9, 11, 10,  8,  2,  7,  5,  4,  1,  6,  3])

In [5]:
df.groupby("sexo_paciente").size()

sexo_paciente
F    3309
M    4134
dtype: int64

In [6]:
df.groupby("raca_cor_paciente").size()

raca_cor_paciente
1     3903
2      271
3     2519
4      454
5       32
99     264
dtype: int64

In [7]:
df["idade_paciente"].unique()

array([ 28,  21,  26,  35,  64,  75,  60,  63,  72,  80,  49,  33,  46,
        59,  23,  27,  69,  29,  25,  32,  24,  57,  42,  45,  40,  34,
        38,  36,  30,  18,  53,  61,  41,  68,  22,  39,  77,  47,  44,
        31,  74,  58,  43,  50,  62,  52,   5,  12, 105,  73,  20,  70,
        17,  37,  19,   8,  48,  67,  66,  76,  95,  85,  56,   0,  11,
        83,  14,  13,  51,   1,  79,   4,  15,  71,  86,  81,   6,   3,
        88,  82,  55,  10,  54,  65,   9,   7,  84,  78,  16,  97,  87,
        89,   2,  94,  92,  91])

In [8]:
bins = [0, 17, 29, 44, 59, 120]
labels = ["0–17", "18–29", "30–44", "45–59", "60+"]

df["faixa_etaria"] = pd.cut(
    df["idade_paciente"],
    bins=bins,
    labels=labels
)

In [9]:
df["faixa_etaria"].value_counts().sort_index()

faixa_etaria
0–17      365
18–29    1529
30–44    2677
45–59    1260
60+      1593
Name: count, dtype: int64

In [10]:
df.groupby("ano").size().sum()

7443

In [11]:
df = df.sort_values("ano")
df

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus,faixa_etaria
3867,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3884,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3885,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3886,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3887,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2627,2025,7,PE,Pernambuco,2603454,Camaragibe,6685676,NaN,NaN,Z726,M,30,2,0,0,2603454,Camaragibe,54771000,1,30–44
2626,2025,7,PE,Pernambuco,2603454,Camaragibe,6685676,NaN,NaN,Z726,M,30,2,0,0,2603454,Camaragibe,54771000,1,30–44
2621,2025,9,SC,Santa Catarina,4208906,Jaraguá do Sul,5916968,NaN,NaN,F630,M,34,1,0,0,4208906,Jaraguá do Sul,89251590,1,30–44
2616,2025,3,PR,Paraná,4119509,Piraquara,5260981,NaN,NaN,F630,M,47,3,0,0,4119509,Piraquara,83301620,1,45–59
5870,2025,9,SC,Santa Catarina,4207007,Içara,2623218,NaN,NaN,F630,M,29,1,0,0,4207007,Içara,99999999,1,18–29

In [12]:
df.groupby("sigla_uf").size().sort_values(ascending=False)

sigla_uf
SP    3273
RO    1166
MG     520
RS     434
PR     267
SC     247
PE     233
GO     181
PB     136
PI     109
CE     108
BA     108
MS      98
PA      98
RJ      95
MA      80
MT      71
AL      64
TO      52
AM      41
SE      21
DF      12
RN       9
RR       8
ES       7
AC       5
dtype: int64

In [13]:
df.value_counts("nome_municipio_cnes")

nome_municipio_cnes
São Paulo                  2341
Rolim de Moura             1152
Curitiba                    130
São Caetano do Sul          117
Recife                       95
                           ...
Mirante do Paranapanema       1
Mirassol d'Oeste              1
Mogi das Cruzes               1
Mucajaí                       1
Lassance                      1
Name: count, Length: 521, dtype: int64

In [14]:
df["id_municipio"].unique()

array([3543907, 3550308, 5214606, 3526803, 3170107, 3520509, 2516904,
       1302603, 3304557, 2615003, 3170206, 3518800, 3540754, 4319901,
       4317202, 3136207, 4307906, 2406106, 2501005, 5003702, 3529401,
       4321402, 4209300, 3548500, 3509502, 3155801, 3518602, 1713205,
       3110004, 2611606, 3525904, 2604601, 3302007, 3524105, 2105302,
       3304409, 2604106, 3526902, 4314902, 5213103, 4314407, 3107703,
       2500536, 2700300, 5200209, 2304103, 3132206, 3145109, 2207801,
       2408102, 2928000, 3106200, 5007695, 4309001, 2404200, 3169356,
       3508504, 2913606, 2613602, 5218805, 2208304, 3527108, 4304705,
       1400175, 2603009, 3551009, 3538709, 3507506, 3525300, 1501253,
       3114204, 2508901, 2103307, 3137205, 3302601, 3117504, 4202404,
       2208007, 3154606, 3119401, 2611101, 2605707, 5002704, 3548708,
       2111508, 3506003, 2613503, 2933208, 3131901, 4102406, 2914505,
       3300704, 5300108, 1504059, 1501402, 3507902, 1502707, 3554102,
       3546603, 2103703, 2303709, 3131307, 3522505, 2600054, 4106902,
       4204608, 3135001, 2111300, 3145901, 5108600, 3118601, 4322509,
       3530607, 1200203, 2515302, 4318804, 2210409, 3500501, 3121605,
       4105904, 3135803, 2922003, 4209102, 1505502, 5005707, 1100338,
       3129509, 2402006, 3201209, 4316907, 3547809, 2312908, 3518701,
       3501905, 2207009, 4119152, 4209003, 4311809, 3118809, 3131703,
       2101004, 2201200, 3133105, 2304400, 5208806, 4302220, 3111200,
       2311504, 4205407, 3548807, 3120904, 1500404, 3547304, 3538006,
       2509305, 3139300, 2600104, 2917607, 2609600, 2208205, 5007950,
       4203600, 4320008, 3138104, 2105500, 2516201, 2511301, 3517406,
       4318309, 3506102, 2921203, 2914802, 2200608, 3523404, 2306900,
       2912202, 5102678, 3148103, 3105608, 2301703, 5201405, 2302503,
       3514502, 2802908, 5107909, 2905701, 1507607, 3135100, 2611309,
       5205109, 4202008, 3533403, 3151701, 1100122, 1100288, 3549805,
       3142106, 2300150, 3170800, 2307650, 3150802, 4208906, 2802106,
       4311403, 3510807, 3516309, 2601409, 2106755, 1400308, 4119509,
       2500700, 3143104, 5006606, 4303905, 2906006, 1302504, 5211503,
       3141801, 2906873, 1718204, 4315701, 2608255, 3552205, 2910057,
       2905206, 3534401, 3541000, 3543303, 4300604, 1502954, 3169703,
       2929909, 2702355, 4318507, 5006002, 3148707, 5105101, 5105150,
       3156007, 4308201, 5217104, 4212106, 2702405, 3101904, 4314100,
       4122404, 2607208, 3530201, 3514106, 2510808, 3102704, 3529005,
       2614857, 5100250, 3510401, 4323002, 5107925, 5208707, 3127370,
       2800308, 3505807, 2211100, 4310108, 3306206, 5104104, 2104800,
       2504009, 3159902, 1506195, 2103208, 3133808, 4307708, 4318705,
       1303106, 2504702, 3549904, 3109006, 1716653, 5108402, 4215802,
       1503606, 2803500, 2605103, 2908408, 4307005, 5213087, 2302602,
       3108255, 2927408, 5105622, 5106422, 1506807, 2918407, 2800670,
       3160405, 2804805, 2903508, 3134202, 3116605, 3301009, 3543402,
       1100304, 4211306, 3104205, 2930204, 5105606, 5213806, 4315107,
       4202800, 5003207, 2202000, 4304630, 3556206, 3516200, 3303302,
       2908309, 2309458, 5103403, 3205309, 2503209, 4309100, 3511102,
       3107406, 3526407, 3516705, 3143302, 2100600, 3118304, 3145208,
       2516102, 2504801, 2112100, 5200258, 5218003, 2210706, 3501608,
       3544103, 2103257, 5105259, 2308302, 5106752, 1721000, 4315602,
       4317509, 2504603, 3144300, 1100254, 3130101, 3502705, 1504422,
       3521903, 3108602, 2919504, 4321501, 2101400, 3107109, 1100205,
       3535507, 2916500, 4208203, 2603926, 4207304, 2610707, 3507001,
       4117701, 2112209, 5107040, 2604007, 1506708, 4116901, 2928901,
       2503704, 3200201, 3526704, 1702109, 4306601, 4304606, 3502804,
       5007935, 2314102, 3152105, 4104303, 3524006, 3527306, 3552908,
       2506905, 4113205, 2613404, 3114501, 2513927, 3139607, 3505708,
       2614501, 2507507, 3555109, 2914604, 2900108, 3513702, 2706703,
       5106372, 4322202, 2704302, 3135209, 2704500, 3140001, 2512101,
       4322608, 3151206, 3205200, 3505302, 3539301, 4302105, 2605202,
       3557006, 2203701, 3148004, 2918001, 3144805, 2616308, 4202909,
       2902609, 4321600, 3504602, 3168606, 3539509, 2307304, 2613909,
       2306207, 4101804, 5008305, 4124004, 4306106, 3509601, 4206504,
       5208004, 3555604, 1100049, 2211001, 2311801, 4103701, 3513801,
       3511706, 2607901, 2100303, 5217609, 3167202, 2904605, 3534609,
       2303402, 2605152, 5211800, 2804904, 3137502, 4306767, 4119608,
       3508801, 4305108, 2207900, 2705002, 3505906, 3169307, 1100452,
       5220108, 3501301, 3556107, 2806701, 3551702, 3140704, 4109609,
       1301209, 4205456, 2310258, 3162807, 3171006, 5208400, 2201507,
       2411205, 2900702, 3163805, 2913804, 2311405, 3510609, 2929107,
       2412609, 3504305, 1303304, 2110203, 3553658, 4203956, 3152006,
       2512804, 1506187, 3139409, 2930709, 2405801, 3122306, 3513405,
       2807402, 3544202, 2902104, 2929503, 2309607, 2210607, 3522604,
       4105409, 4125704, 1507953, 4313409, 4207007, 3503307, 4316808,
       2610509, 5201108, 3542800, 4216602, 1200401, 3147105, 2507101,
       4303004, 2603454, 1304203, 3169901, 3524402])

## São Paulo state

Aggregate outpatient visits by municipality to identify where gambling- and betting-related healthcare visits were recorded across the state.

In [15]:
df_sp = df[df["sigla_uf"] == "SP"]
df_sp

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus,faixa_etaria
3867,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3884,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3885,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3886,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
3887,2015,2,SP,São Paulo,3543907,Rio Claro,2031884,NaN,NaN,F630,F,25,1,0,0,3543907,Rio Claro,13503260,1,18–29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5477,2025,8,SP,São Paulo,3501905,Amparo,6628613,NaN,NaN,Z726,F,72,3,0,0,3501905,Amparo,13901150,1,60+
5520,2025,5,SP,São Paulo,3505708,Barueri,2024403,F630,NaN,NaN,M,27,1,0,1,3505708,Barueri,6401126,1,18–29
2573,2025,5,SP,São Paulo,3501905,Amparo,6628613,NaN,NaN,Z726,F,71,3,0,0,3501905,Amparo,13900100,1,60+
5486,2025,6,SP,São Paulo,3505906,Batatais,2038188,F630,NaN,NaN,M,37,4,0,0,3505906,Batatais,14300033,1,30–44
5487,2025,6,SP,São Paulo,3524402,Jacareí,2793431,F630,NaN,NaN,M,33,1,0,0,3524402,Jacareí,12322290,1,30–44

In [16]:
df_sp["nome_municipio_cnes"].value_counts()

nome_municipio_cnes
São Paulo                  2341
São Caetano do Sul          117
Praia Grande                 76
Indaiatuba                   68
São Bernardo do Campo        42
                           ...
Taciba                        1
Pirassununga                  1
Votorantim                    1
Mirante do Paranapanema       1
Jacareí                       1
Name: count, Length: 95, dtype: int64

In [17]:
df_sp.to_csv("df_sp_state.csv")

## São Paulo city

Analyze outpatient records for the city of São Paulo to examine the geographic distribution of gambling- and betting-related healthcare visits.

In [18]:
df_capital = df_sp[df_sp["nome_municipio_cnes"] == "São Paulo"]

In [19]:
df_capital

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus,faixa_etaria
1380,2015,8,SP,São Paulo,3550308,São Paulo,2078015,F630,NaN,NaN,F,30,1,0,0,3550308,São Paulo,5401000,1,30–44
5258,2015,8,SP,São Paulo,3550308,São Paulo,3384292,NaN,NaN,F630,F,47,1,0,0,3550308,São Paulo,3427070,1,45–59
3850,2015,11,SP,São Paulo,3550308,São Paulo,3384292,NaN,NaN,F630,F,47,1,0,0,3550308,São Paulo,3427070,1,45–59
3852,2015,11,SP,São Paulo,3550308,São Paulo,3384292,NaN,NaN,F630,F,47,1,0,0,3550308,São Paulo,3427070,1,45–59
3863,2015,11,SP,São Paulo,3550308,São Paulo,3384292,NaN,NaN,F630,F,47,1,0,0,3550308,São Paulo,3427070,1,45–59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,2025,11,SP,São Paulo,3550308,São Paulo,5731194,F630,NaN,NaN,F,23,1,0,0,3550308,São Paulo,4463030,1,18–29
2809,2025,11,SP,São Paulo,3550308,São Paulo,5731194,F630,NaN,NaN,M,42,3,0,0,3550308,São Paulo,4463030,1,30–44
2888,2025,10,SP,São Paulo,3550308,São Paulo,6148387,F630,NaN,NaN,F,60,3,0,0,3550308,São Paulo,2634070,1,60+
5426,2025,4,SP,São Paulo,3550308,São Paulo,7861249,F630,NaN,NaN,M,9,1,0,0,3550308,São Paulo,2031200,1,0–17
2819,2025,11,SP,São Paulo,3550308,São Paulo,5731194,F630,NaN,NaN,M,21,3,0,0,3550308,São Paulo,4463030,1,18–29

In [20]:
df_capital.shape

(2341, 20)

In [21]:
df_capital["nome_municipio_cnes"].unique()

array(['São Paulo'], dtype=object)

In [22]:
df_capital.to_csv("df_capital_city.csv", index=False)

In [23]:
df_capital["nome_municipio_cnes"]

1380    São Paulo
5258    São Paulo
3850    São Paulo
3852    São Paulo
3863    São Paulo
          ...
2795    São Paulo
2809    São Paulo
2888    São Paulo
5426    São Paulo
2819    São Paulo
Name: nome_municipio_cnes, Length: 2341, dtype: object

In [26]:
df_capital.value_counts("id_estabelecimento_cnes", ascending=False)

id_estabelecimento_cnes
2078015    2162
2812703      47
2815427      20
3384292      16
5731194      15
3025438      10
2786508       8
2815435       7
3906388       6
2068923       5
2028816       4
6586147       4
6148387       2
4049861       2
5743583       2
6245838       2
6380417       2
7861249       2
3614948       2
3313344       2
9664815       2
2787547       2
2787423       2
2752360       2
6269567       1
2077426       1
6924972       1
2786524       1
6336302       1
2066572       1
2786532       1
2788314       1
2786540       1
6066585       1
2787318       1
4049829       1
6195008       1
Name: count, dtype: int64