# Inspect ICD-10 diagnosis fields

This notebook examines how gambling-related ICDs diagnoses are recorded in the outpatient dataset.

The dataset has already been filtered to include records containing gambling-related diagnoses. 

The purpose of this notebook is to verify in which diagnosis fields these codes appear and whether the same record can contain both diagnoses.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sia-data.csv")

In [3]:
df.head()

,ano,mes,sigla_uf,nome_uf,id_municipio,nome_municipio,id_estabelecimento_cnes,cid_principal_subcategoria,cid_secundario_subcategoria,cid_causas_associadas_subcategoria,sexo_paciente,idade_paciente,raca_cor_paciente,indicador_uf_residencia_paciente,indicador_municipio_residencia_paciente,id_municipio_cnes,nome_municipio_cnes,cep,indicador_vinculo_sus
0,2024,5,SP,São Paulo,3550308,São Paulo,2078015,F630,NaN,NaN,M,28,1,0,1,3550308,São Paulo,5403010,1
1,2022,10,MA,Maranhão,2106755,Miranda do Norte,6569862,F630,NaN,NaN,M,21,3,0,0,2106755,Miranda do Norte,65495000,1
2,2022,9,BA,Bahia,2905701,Camaçari,7781555,F630,NaN,NaN,M,26,3,0,0,2905701,Camaçari,42809382,1
3,2024,10,SC,Santa Catarina,4209003,Joaçaba,3757412,NaN,NaN,F630,M,35,3,0,0,4209003,Joaçaba,89600000,1
4,2024,12,RO,Rondônia,1100288,Rolim de Moura,7217765,F630,NaN,NaN,F,64,3,0,0,1100288,Rolim de Moura,76940000,1

In [ ]:
df.value_counts

In [7]:
cids = ["F630", "Z726"]

for cid in cids:
    print(f"\nCID {cid}")
    print("cid_principal_subcategoria:",
          (df["cid_principal_subcategoria"] == cid).sum())
    print("cid_secundario_subcategoria:",
          (df["cid_secundario_subcategoria"] == cid).sum())
    print("cid_causas_associadas_subcategoria:",
          (df["cid_causas_associadas_subcategoria"] == cid).sum())

CID F630
cid_principal_subcategoria: 5292
cid_secundario_subcategoria: 0
cid_causas_associadas_subcategoria: 1867

CID Z726
cid_principal_subcategoria: 140
cid_secundario_subcategoria: 0
cid_causas_associadas_subcategoria: 144

In [9]:
cols = [
    "cid_principal_subcategoria",
    "cid_secundario_subcategoria",
    "cid_causas_associadas_subcategoria",
]

tem_f630 = (
    (df["cid_principal_subcategoria"] == "F630") |
    (df["cid_secundario_subcategoria"] == "F630") |
    (df["cid_causas_associadas_subcategoria"] == "F630")
)

tem_z726 = (
    (df["cid_principal_subcategoria"] == "Z726") |
    (df["cid_secundario_subcategoria"] == "Z726") |
    (df["cid_causas_associadas_subcategoria"] == "Z726")
)

df_ambos = df[tem_f630 & tem_z726]
df_ambos

Empty DataFrame
Columns: [ano, mes, sigla_uf, nome_uf, id_municipio, nome_municipio, id_estabelecimento_cnes, cid_principal_subcategoria, cid_secundario_subcategoria, cid_causas_associadas_subcategoria, sexo_paciente, idade_paciente, raca_cor_paciente, indicador_uf_residencia_paciente, indicador_municipio_residencia_paciente, id_municipio_cnes, nome_municipio_cnes, cep, indicador_vinculo_sus]
Index: []

In [17]:
len(df_ambos)

0